version: "3.8"

services:
  postgres:
    image: postgres:13.2
    container_name: procharity_postgres
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    image: nginx:1.23.3-alpine
    container_name: procharity_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env

volumes:
  local_postgres_data:
