[tool.poetry]
name = "procharity-back-2-0"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "procharity_back_2"}]

[tool.poetry.dependencies]
python = "3.11"
poetry = "^1.4.2"
fastapi = "^0.95.0"
uvicorn = "^0.21.1"
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
