version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: procharity_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
