name: Stage Deploy

concurrency:
  group: stage_deploy
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: deploy-prod
      label: prod
    secrets: inherit
