name: Stage bot frontend

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - develop
      - feature/deployment-of-admin-tools

  pull_request:
    branches:
      - master
      - develop
      - feature/deployment-of-admin-tools
    # types: [ closed ]

env:
  REGISTRY: ghcr.io
  DEPLOY_PATH: /code
  IMAGE_NAME_FRONT: procharity_bot_front
  OWNER_LC: studio-yandex-practicum


jobs:
  build_and_push_to_ghcr:
    name: Push front Docker image to Github Container Registry
    runs-on: ubuntu-latest
    environment:
      name: stage_deploy
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Front to ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          file: ./infra/Dockerfile_front
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME_FRONT }}:prod
