name: Test Workflow

on:
  push:
    branches:
      - fix/frontend_only_when_changed
    paths:
      - 'front/**'

  workflow_dispatch:

env:
  GREETING: Hello!

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display greeting message
        run: echo ${{ env.GREETING }}